server {
    listen 80;
    listen [::]:80;
    server_name modelarcve.com www.modelarcve.com;

    root /var/www/modelarc/apps/web/dist/spa;
    index index.html;

    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?|otf|ttf|eot|webp|avif)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    access_log /var/log/nginx/modelarcve.access.log;
    error_log  /var/log/nginx/modelarcve.error.log;
}
